stages:
  - test

before_script:
    - apt-get update && apt-get install -y build-essential

unittest:
  stage: test
  image: python:$PYTHON_VERSIONS
  parallel:
    matrix:
      - PYTHON_VERSIONS: [ "3.7", "3.8", "3.9", "3.10" ] # 3.11 limited by drivability-checker
  script:
    - pip install -e .
    - cd $CI_PROJECT_DIR/tests && python -m unittest
