image: python:3.8

stages:
  - style
  - test
  - publish
  - deploy

before_script:
    - apt-get update && apt-get install -y build-essential
    - apt-get install -y libgl1
    - pip install --upgrade pip
    - pip install -e .

black:
  stage: style
  needs: []
  image: pyfound/black:23.1.0
  before_script: []
  cache: []
  allow_failure: true
  script:
    - black --check --verbose --diff --color commonroad_crime
    - black --check --verbose --diff --color tests

unittest:
  stage: test
  image: python:$PYTHON_VERSIONS
  parallel:
    matrix:
      - PYTHON_VERSIONS: ["3.8", "3.9", "3.10" ] # 3.11 limited by drivability-checker
  script:
    - cd $CI_PROJECT_DIR/tests && python -m unittest

### publish documentation ###
pages:
  # Push the latest documentation of the master branch to the GitLab Pages documentation
  # at https://cps.pages.gitlab.lrz.de/commonroad-criticality-measures
  stage: publish
  script:
    - pip install -r ./docs/requirements_doc.txt
    - cd docs/sphinx
    - make html
    - mv ./build/html ../../public
  artifacts:
    paths:
      - public
  environment:
    name: Gitlab Pages
    url: https://cps.pages.gitlab.lrz.de/commonroad-criticality-measures
  only:
    - master

push_to_internal_pipy_registry:
  stage: deploy
  when: manual
  only:
    - develop
  script:
    - python -m pip install --upgrade setuptools wheel twine
    - python setup.py sdist bdist_wheel
    # Configure the GitLab PyPI repository URL and your credentials for twine
    - python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi -u gitlab-ci-token -p ${CI_JOB_TOKEN} dist/*
    -     - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --skip-existing --repository-url https://gitlab.lrz.de/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/* --verbose

push_to_external_pipy_test_registry:
  stage: deploy
  when: manual
  only:
    - master
  script:
    - python -m pip install --upgrade pip
    - python -m pip install --upgrade setuptools wheel twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CR_PYPI_TEST_API_TOKEN} TWINE_USERNAME=__token__ python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* --verbose

push_to_external_pipy_release_registry:
  stage: deploy
  when: manual
  only:
    - master
  script:
    - python -m pip install --upgrade pip
    - python -m pip install --upgrade setuptools wheel twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CR_PYPI_RELEASE_API_TOKEN} TWINE_USERNAME=__token__ python -m twine upload dist/* --verbose



