stages:
  - test

image: continuumio/anaconda3

before_script:
    - apt-get update && apt-get install -y build-essential
    - conda create -n commonroad-py37 python=3.7 -y
    - source activate commonroad-py37
    - conda info

unittest:
  stage: test
  script:
    - pip install -e .
    - cd $CI_PROJECT_DIR/tests && python -m unittest
