stages:
  - test

image: continuumio/anaconda3

before_script:
    - apt-get update && apt-get install -y build-essential
    - conda create -n commonroad-py37 python=3.7 -y
    - source activate commonroad-py37
    - conda info
    - pip install -e .

    # install commonroad-reach
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de/".insteadOf "git@gitlab.lrz.de:"
    - pip install git+ssh://git@gitlab.lrz.de/cps/commonroad-reachable-set

unittest:
  stage: test
  script:
    - cd $CI_PROJECT_DIR/tests && python -m unittest
