image: python:3.8

stages:
  - style_check
  - test
  - publish

before_script:
    - apt-get update && apt-get install -y build-essential
    - pip install --upgrade pip
    - pip install -e .

unittest:
  stage: test
  image: python:$PYTHON_VERSIONS
  parallel:
    matrix:
      - PYTHON_VERSIONS: [ "3.7", "3.8", "3.9", "3.10" ] # 3.11 limited by drivability-checker
  script:
    - cd $CI_PROJECT_DIR/tests && python -m unittest

### publish documentation ###
pages:
  # Push the latest documentation of the master branch to the GitLab Pages documentation
  # at https://cps.pages.gitlab.lrz.de/commonroad-criticality-measures
  stage: publish
  script:
    - pip install -r ./docs/requirements_doc.txt
    - cd docs/sphinx
    - make html
    - mv ./build/html ../../public
  artifacts:
    paths:
      - public
  environment:
    name: Gitlab Pages
    url: https://cps.pages.gitlab.lrz.de/commonroad-criticality-measures
  only:
    - master
